Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
title_id = "11"
params = {"encoding": "json", "include": "years"}

url = f"https://api.trove.nla.gov.au/v3/newspaper/title/{title_id}"
response = requests.get(url, params=params, headers=headers)
data = response.json()
year_totals = data["year"]

# Show the first 5 values
year_totals[0:5]
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      2[0m params [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mencoding[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mjson[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124minclude[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124myears[39m[38;5;124m"[39m}
[1;32m      4[0m url [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mhttps://api.trove.nla.gov.au/v3/newspaper/title/[39m[38;5;132;01m{[39;00mtitle_id[38;5;132;01m}[39;00m[38;5;124m"[39m
[0;32m----> 5[0m response [38;5;241m=[39m requests[38;5;241m.[39mget(url, params[38;5;241m=[39mparams, headers[38;5;241m=[39m[43mheaders[49m)
[1;32m      6[0m data [38;5;241m=[39m response[38;5;241m.[39mjson()
[1;32m      7[0m year_totals [38;5;241m=[39m data[[38;5;124m"[39m[38;5;124myear[39m[38;5;124m"[39m]

[0;31mNameError[0m: name 'headers' is not defined

